export const ADD_MEMBER_LOADING = "ADD_MEMBER_LOADING";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_ERROR = "ADD_MEMBER_ERROR";


export const GET_MEMBER_LOADING = "GET_MEMBER_LOADING";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_ERROR = "GET_MEMBER_ERROR";

export const DEL_MEMBER_LOADING = "DEL_MEMBER_LOADING";
export const DEL_MEMBER_SUCCESS = "DEL_MEMBER_SUCCESS";
export const DEL_MEMBER_ERROR = "DEL_MEMBER_ERROR";


export const UPDATE_MEMBER_LOADING = "UPDATE_MEMBER_LOADING";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_ERROR = "UPDATE_MEMBER_ERROR";


export const GET_TOKEN = "GET_TOKEN";


